// For News Component
export const NEWS_LOAD_POST_LIST_DATA = 'NEWS_LOAD_POST_LIST_DATA';
export const NEWS_LOAD_POST_LIST_DATA_SUCCESS = 'NEWS_LOAD_POST_LIST_DATA_SUCCESS';
export const NEWS_LOAD_POST_LIST_DATA_FAIL = 'NEWS_LOAD_POST_LIST_DATA_FAIL';
export const NEWS_COUNT_POST_TOTAL = 'NEWS_COUNT_POST_TOTAL';

// For PostDetail Component
export const POST_DETAIL_LOAD_POST_DATA = 'POST_DETAIL_LOAD_POST_DATA';
export const POST_DETAIL_LOAD_POST_DATA_SUCCESS = 'POST_DETAIL_LOAD_POST_DATA_SUCCESS';
export const POST_DETAIL_LOAD_POST_DATA_FAIL = 'POST_DETAIL_LOAD_POST_DATA_FAIL';