export const LOAD_POST_LIST_DATA = 'LOAD_POST_LIST_DATA';
export const LOAD_POST_LIST_DATA_SUCCESS = 'LOAD_POST_LIST_DATA_SUCCESS';
export const LOAD_POST_LIST_DATA_FAIL = 'LOAD_POST_LIST_DATA_FAIL';
export const COUNT_POST_TOTAL = 'COUNT_POST_TOTAL';
